### PR TITLE
add ray tune packages

### PR DESCRIPTION
**Pull request by MichaelClifford**
Adding additional ray packages to Pipfile and Pipfile.lock needed to use the Ray Tune tooling with Jupyterhub. 

These changes are also being made in the notebook image here: https://github.com/thoth-station/ray-ml-notebook/pull/12

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@harshad16 @erikerlandson

**Review by harshad16 — APPROVED** [review]
This is tested and working
Related-to: https://github.com/thoth-station/ray-ml-notebook/issues/13
Thanks :100:

**Pull request merged**
